package org.mehdimt.v2rayfinder;

import android.app.Activity;
import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.Editable;
import android.text.InputType;
import android.text.TextWatcher;
import android.view.Gravity;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;

import org.json.JSONArray;
import org.json.JSONObject;
import org.mehdimt.v2rayfinder.registry.NativeSourceRefreshBridge;
import org.mehdimt.v2rayfinder.runtime.NativeScanBridge;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class MainActivity extends Activity {
    private static final int PAGE_SIZE = 10;
    private static final String FILTER_ALL = "ALL";
    private static final String[] PROTOCOL_FILTERS = {FILTER_ALL, "VLESS", "VMESS", "TROJAN", "SS"};
    private final int bg = Color.rgb(7, 12, 27), surface = Color.rgb(19, 29, 51), surface2 = Color.rgb(33, 47, 82), surface3 = Color.rgb(24, 39, 71), text = Color.rgb(241, 246, 255), muted = Color.rgb(160, 178, 205), accent = Color.rgb(17, 145, 255), warning = Color.rgb(255, 184, 77), danger = Color.rgb(214, 76, 76);
    private EditText tokenInput, limitInput, timeoutInput, searchInput;
    private CheckBox healthBox, realCheckBox;
    private Button startButton, stopButton, copyButton, protocolButton, refreshButton;
    private ProgressBar progressBar;
    private TextView statusText, refreshStatus, fetchedText, uniqueText, healthyText, scoredText;
    private LinearLayout resultList;
    private final List<String> latestConfigs = new ArrayList<>();
    private JSONArray currentItems = new JSONArray(), currentFailedSources = new JSONArray(), currentSourcePerformance = new JSONArray();
    private int currentPage = 0, scanGeneration = 0;
    private String currentProtocolFilter = FILTER_ALL, searchTerm = "";
    private boolean scanCancelled = false, running = false;

    @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); getWindow().setStatusBarColor(bg); getWindow().setNavigationBarColor(bg); setContentView(buildUi()); }

    private View buildUi() {
        ScrollView scroll = new ScrollView(this); scroll.setFillViewport(true); scroll.setBackgroundColor(bg); scroll.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        LinearLayout root = new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setPadding(dp(16), dp(18), dp(16), dp(18)); root.setGravity(Gravity.CENTER_HORIZONTAL); root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); scroll.addView(root);
        LinearLayout header = card(surface3, 22); header.setOrientation(LinearLayout.VERTICAL); header.addView(label("V2Ray Finder", 30, text, true, false)); header.addView(label("یابنده هوشمند کانفیگ‌های V2Ray برای کاربران ایران", 14, muted, false, true)); header.addView(label("اسکن native Kotlin، بررسی TCP، تست واقعی xray و کپی سریع", 12, muted, false, true)); root.addView(header, matchWrap());
        LinearLayout controls = card(surface, 22); controls.setOrientation(LinearLayout.VERTICAL); controls.setPadding(dp(14), dp(14), dp(14), dp(14));
        tokenInput = input("توکن گیت‌هاب اختیاری", true, true); controls.addView(tokenInput, matchHeight(54));
        LinearLayout row = new LinearLayout(this); row.setOrientation(LinearLayout.HORIZONTAL); row.setPadding(0, dp(12), 0, dp(8)); row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);
        limitInput = input("۶۰", false, false); limitInput.setText("60"); limitInput.setInputType(InputType.TYPE_CLASS_NUMBER);
        timeoutInput = input("۵", false, false); timeoutInput.setText("5"); timeoutInput.setInputType(InputType.TYPE_CLASS_NUMBER | InputType.TYPE_NUMBER_FLAG_DECIMAL);
        row.addView(inputGroup("تعداد کانفیگ‌ها", "حداکثر تعداد برای نمایش", limitInput), weight()); row.addView(space(dp(10), 1)); row.addView(inputGroup("مهلت اتصال", "ثانیه برای هر منبع/سرور", timeoutInput), weight()); controls.addView(row);
        healthBox = checkBox("بررسی سلامت TCP", true); controls.addView(healthBox);
        realCheckBox = checkBox("Real Validation با xray — کندتر، دقیق‌تر", false); realCheckBox.setEnabled(true); controls.addView(realCheckBox);
        TextView xrayHint = label(isXrayAvailable() ? "xray داخل APK پیدا شد. اگر تیک بزنید، backend واقعاً xray را درخواست می‌کند." : "xray در این لحظه در nativeLibraryDir دیده نشد. با این حال تیک xray به backend ارسال می‌شود تا خطای واقعی گزارش شود.", 11, muted, false, true); xrayHint.setPadding(0, 0, 0, dp(8)); controls.addView(xrayHint);
        refreshButton = button("به‌روزرسانی منابع از GitHub", surface2); refreshButton.setOnClickListener(v -> refreshSourcesNow()); controls.addView(refreshButton, matchHeight(44));
        refreshStatus = label("برای دریافت sourceهای جدید این دکمه را بزن.", 11, muted, false, true); refreshStatus.setPadding(0, dp(6), 0, dp(8)); controls.addView(refreshStatus);
        searchInput = input("جستجو در کانفیگ، منبع یا پروتکل", false, true); searchInput.addTextChangedListener(new TextWatcher() { @Override public void beforeTextChanged(CharSequence s, int start, int count, int after) { } @Override public void onTextChanged(CharSequence s, int start, int before, int count) { searchTerm = s == null ? "" : s.toString().trim(); currentPage = 0; if (currentItems.length() > 0) renderCurrentPage(); } @Override public void afterTextChanged(Editable s) { } }); controls.addView(searchInput, matchHeight(52));
        protocolButton = button("فیلتر پروتکل: همه", surface2); protocolButton.setOnClickListener(v -> cycleProtocolFilter()); LinearLayout.LayoutParams protoLp = matchHeight(44); protoLp.setMargins(0, dp(8), 0, 0); controls.addView(protocolButton, protoLp);
        LinearLayout buttons = new LinearLayout(this); buttons.setOrientation(LinearLayout.HORIZONTAL); buttons.setPadding(0, dp(10), 0, 0); buttons.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); startButton = button("شروع اسکن", accent); stopButton = button("توقف", danger); copyButton = button("کپی همه", surface2); stopButton.setEnabled(false); copyButton.setEnabled(false); startButton.setOnClickListener(v -> startScan()); stopButton.setOnClickListener(v -> stopScan()); copyButton.setOnClickListener(v -> copyResults()); buttons.addView(startButton, weight()); buttons.addView(space(dp(8), 1)); buttons.addView(stopButton, weight()); buttons.addView(space(dp(8), 1)); buttons.addView(copyButton, weight()); controls.addView(buttons); root.addView(controls, matchWrap());
        LinearLayout stats = new LinearLayout(this); stats.setOrientation(LinearLayout.HORIZONTAL); stats.setPadding(0, dp(12), 0, dp(12)); stats.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); fetchedText = statCard("دریافتی", stats); uniqueText = statCard("یکتا", stats); healthyText = statCard("سالم", stats); scoredText = statCard("رتبه‌بندی", stats); root.addView(stats, matchWrap());
        LinearLayout statusCard = card(surface, 18); statusCard.setOrientation(LinearLayout.VERTICAL); statusText = label("آماده است. مسیر فعال native Kotlin است.", 14, text, false, true); progressBar = new ProgressBar(this, null, android.R.attr.progressBarStyleHorizontal); progressBar.setMax(100); progressBar.setProgress(0); statusCard.addView(statusText); statusCard.addView(progressBar, matchHeight(14)); root.addView(statusCard, matchWrap());
        resultList = new LinearLayout(this); resultList.setOrientation(LinearLayout.VERTICAL); resultList.setPadding(0, dp(12), 0, 0); resultList.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); root.addView(resultList, matchWrap());
        return scroll;
    }

    private void refreshSourcesNow() { refreshButton.setEnabled(false); refreshStatus.setTextColor(muted); refreshStatus.setText("در حال دریافت registry از GitHub..."); String token = tokenInput.getText().toString(); new Thread(() -> { String message; boolean ok; try { JSONObject result = new JSONObject(NativeSourceRefreshBridge.refreshSourcesNow(this, token)); ok = result.optBoolean("ok", false); int active = result.optInt("active_sources", 0); message = result.optString("message", ok ? "منابع به‌روزرسانی شد." : "به‌روزرسانی ناموفق بود.") + " منابع فعال: " + active; } catch (Exception exc) { ok = false; message = "به‌روزرسانی ناموفق بود: " + exc.getMessage(); } boolean finalOk = ok; String finalMessage = message; runOnUiThread(() -> { refreshStatus.setText(finalMessage); refreshStatus.setTextColor(finalOk ? accent : muted); refreshButton.setEnabled(!running); }); }).start(); }

    private void startScan() { latestConfigs.clear(); currentItems = new JSONArray(); currentFailedSources = new JSONArray(); currentSourcePerformance = new JSONArray(); currentPage = 0; resultList.removeAllViews(); setStats("0", "0", "0", "0"); scanCancelled = false; final int runId = ++scanGeneration; setBusy(true); boolean realValidation = realCheckBox != null && realCheckBox.isChecked(); statusText.setText("در حال اسکن... xrayRequested=" + realValidation + " xrayAvailable=" + isXrayAvailable()); progressBar.setIndeterminate(true); int limit = parseInt(limitInput.getText().toString(), 60); double timeout = parseDouble(timeoutInput.getText().toString(), 5.0); boolean health = healthBox.isChecked(); String token = tokenInput.getText().toString(); new Thread(() -> { try { String json = NativeScanBridge.scan(this, limit, timeout, health, realValidation, token); JSONObject payload = new JSONObject(json); runOnUiThread(() -> { if (scanCancelled || runId != scanGeneration) return; showResults(payload, realValidation); }); } catch (Exception ex) { runOnUiThread(() -> { if (scanCancelled || runId != scanGeneration) return; showError(ex); }); } }).start(); }
    private void stopScan() { if (!running) return; scanCancelled = true; scanGeneration++; setBusy(false); progressBar.setIndeterminate(false); progressBar.setProgress(0); statusText.setText("اسکن متوقف شد."); }
    private void showResults(JSONObject payload, boolean requested) { try { JSONObject stats = payload.optJSONObject("stats"); if (stats != null) setStats(String.valueOf(stats.optInt("fetched", 0)), String.valueOf(stats.optInt("deduped", 0)), String.valueOf(stats.optInt("healthy", 0)), String.valueOf(stats.optInt("scored", 0))); latestConfigs.clear(); JSONArray configs = payload.optJSONArray("configs"); if (configs != null) for (int i = 0; i < configs.length(); i++) latestConfigs.add(configs.optString(i)); currentItems = payload.optJSONArray("items") == null ? new JSONArray() : payload.optJSONArray("items"); currentFailedSources = payload.optJSONArray("failed_sources") == null ? new JSONArray() : payload.optJSONArray("failed_sources"); currentSourcePerformance = payload.optJSONArray("source_performance") == null ? new JSONArray() : payload.optJSONArray("source_performance"); currentPage = 0; renderCurrentPage(); String done = "تمام شد. " + latestConfigs.size() + " کانفیگ آماده است."; if (stats != null) done += " xrayRequested=" + requested + " strict=" + stats.optBoolean("real_validation_strict", false) + " status=" + stats.optString("xray_status_message", "") + " checked=" + stats.optInt("xray_checked", 0) + " ok=" + stats.optInt("xray_ok", 0) + "."; statusText.setText(done); copyButton.setEnabled(!collectFilteredConfigs().isEmpty()); } catch (Exception ex) { showError(ex); return; } setBusy(false); }

    private void renderCurrentPage() { resultList.removeAllViews(); JSONArray filtered = filteredItems(); int rawTotal = currentItems.length(); int totalItems = filtered.length(); int pageCount = Math.max(1, (int) Math.ceil(totalItems / (double) PAGE_SIZE)); if (currentPage < 0) currentPage = 0; if (currentPage >= pageCount) currentPage = pageCount - 1; copyButton.setEnabled(!running && !collectFilteredConfigs().isEmpty()); if (rawTotal == 0) { resultList.addView(resultRow("نتیجه‌ای پیدا نشد", "xray روشن باشد و نتیجه صفر شود یعنی validation واقعی چیزی را قبول نکرده یا binary مشکل دارد.", "", false)); renderSourcePerformanceIfNeeded(true); renderFailedSourcesIfNeeded(true); return; } if (totalItems == 0) { resultList.addView(resultRow("نتیجه‌ای مطابق فیلتر پیدا نشد", filterSummary(rawTotal, totalItems), "", false)); return; } int start = currentPage * PAGE_SIZE; int end = Math.min(start + PAGE_SIZE, totalItems); resultList.addView(sectionTitle("بهترین کانفیگ‌ها — صفحه " + (currentPage + 1) + " از " + pageCount)); resultList.addView(pagerRow(pageCount)); for (int i = start; i < end; i++) { try { JSONObject item = filtered.getJSONObject(i); String protocol = normalizedProtocol(item.optString("protocol", "?")); String title = "#" + (i + 1) + "  " + protocol + "  •  کیفیت " + item.optString("grade", "?") + "  •  امتیاز " + String.format(Locale.US, "%.2f", item.optDouble("total", 0.0)); String meta = validationLine(item); String src = item.optString("source_label", ""); String url = item.optString("source", ""); if (!src.trim().isEmpty() || !url.trim().isEmpty()) meta += "  •  منبع: " + shortUrl((src + " — " + url).trim()); resultList.addView(resultRow(title, meta, item.optString("config", ""), true)); } catch (Exception ignored) { } } resultList.addView(pagerRow(pageCount)); boolean lastPage = currentPage == pageCount - 1; renderSourcePerformanceIfNeeded(lastPage); renderFailedSourcesIfNeeded(lastPage); statusText.setText("صفحه " + (currentPage + 1) + " از " + pageCount + " — " + totalItems + " کانفیگ مطابق فیلتر."); }
    private String validationLine(JSONObject item) { String tcp = item.optBoolean("tcp_checked", true) ? (item.optBoolean("tcp_ok", false) ? "TCP: OK " + (item.isNull("tcp_latency_ms") ? "" : String.format(Locale.US, "%.0fms", item.optDouble("tcp_latency_ms", 0.0))) : "TCP: FAIL") : "TCP: off"; String xray; if (!item.optBoolean("xray_requested", false)) xray = "Xray: off"; else if (!item.optBoolean("xray_checked", false)) xray = "Xray: skipped " + item.optString("xray_skip_reason", ""); else xray = "Xray: " + (item.optBoolean("xray_ok", false) ? "OK" : "FAIL") + " " + item.optInt("xray_passed_probes", 0) + "/" + item.optInt("xray_total_probes", 0) + " conf " + String.format(Locale.US, "%.2f", item.optDouble("xray_confidence", 0.0)); return tcp.trim() + " | " + xray.trim(); }

    private JSONArray filteredItems() { JSONArray out = new JSONArray(); String q = searchTerm == null ? "" : searchTerm.trim().toLowerCase(Locale.US); for (int i = 0; i < currentItems.length(); i++) try { JSONObject item = currentItems.getJSONObject(i); String protocol = normalizedProtocol(item.optString("protocol", "")); if (!FILTER_ALL.equals(currentProtocolFilter) && !currentProtocolFilter.equals(protocol)) continue; if (!q.isEmpty()) { String config = item.optString("config", "").toLowerCase(Locale.US); String source = (item.optString("source", "") + " " + item.optString("source_label", "") + " " + item.optString("validation_label", "")).toLowerCase(Locale.US); String grade = item.optString("grade", "").toLowerCase(Locale.US); if (!config.contains(q) && !source.contains(q) && !grade.contains(q) && !protocol.toLowerCase(Locale.US).contains(q)) continue; } out.put(item); } catch (Exception ignored) { } return out; }
    private List<String> collectFilteredConfigs() { List<String> configs = new ArrayList<>(); JSONArray filtered = filteredItems(); for (int i = 0; i < filtered.length(); i++) try { String config = filtered.getJSONObject(i).optString("config", ""); if (!config.isEmpty()) configs.add(config); } catch (Exception ignored) { } if (configs.isEmpty() && currentItems.length() == 0) configs.addAll(latestConfigs); return configs; }
    private boolean isFilterActive() { return !FILTER_ALL.equals(currentProtocolFilter) || (searchTerm != null && !searchTerm.trim().isEmpty()); }
    private String filterSummary(int rawTotal, int filteredTotal) { return "پروتکل: " + (FILTER_ALL.equals(currentProtocolFilter) ? "همه" : currentProtocolFilter.toLowerCase(Locale.US)) + " — جستجو: " + (searchTerm == null || searchTerm.trim().isEmpty() ? "بدون جستجو" : searchTerm.trim()) + " — نتیجه: " + filteredTotal + " از " + rawTotal; }
    private void cycleProtocolFilter() { int index = 0; for (int i = 0; i < PROTOCOL_FILTERS.length; i++) if (PROTOCOL_FILTERS[i].equals(currentProtocolFilter)) { index = i; break; } currentProtocolFilter = PROTOCOL_FILTERS[(index + 1) % PROTOCOL_FILTERS.length]; protocolButton.setText("فیلتر پروتکل: " + (FILTER_ALL.equals(currentProtocolFilter) ? "همه" : currentProtocolFilter.toLowerCase(Locale.US))); currentPage = 0; if (currentItems.length() > 0) renderCurrentPage(); }
    private String normalizedProtocol(String value) { String protocol = value == null ? "" : value.trim().toUpperCase(Locale.US); return "SHADOWSOCKS".equals(protocol) ? "SS" : protocol; }
    private void renderSourcePerformanceIfNeeded(boolean shouldShow) { if (!shouldShow || currentSourcePerformance.length() == 0) return; int shown = Math.min(currentSourcePerformance.length(), 5); resultList.addView(sectionTitle("منابع مؤثر — " + currentSourcePerformance.length() + " منبع تحلیل شد")); for (int i = 0; i < shown; i++) try { resultList.addView(sourcePerformanceRow(currentSourcePerformance.getJSONObject(i), i + 1)); } catch (Exception ignored) { } }
    private View sourcePerformanceRow(JSONObject src, int rank) { LinearLayout row = card(surface, 18); row.setOrientation(LinearLayout.VERTICAL); String label = src.optString("label", ""); String url = src.optString("url", ""); String name = label == null || label.trim().isEmpty() ? shortUrl(url) : label; double sourceScore = src.optDouble("source_score", 0.0); String meta = "TCP: " + src.optInt("tcp_ok_count", 0) + "/" + src.optInt("tcp_candidates", 0) + "  •  xray: " + src.optInt("xray_ok_count", 0) + "/" + src.optInt("xray_checked_count", 0) + "  •  trust: " + src.optString("trust", ""); row.addView(label("#" + rank + "  " + name + "  •  امتیاز منبع " + String.format(Locale.US, "%.1f", sourceScore), 14, text, true, true)); row.addView(label(meta, 12, muted, false, true)); row.addView(label(shortUrl(url), 10, muted, false, false)); return row; }
    private void renderFailedSourcesIfNeeded(boolean shouldShow) { if (!shouldShow || currentFailedSources.length() == 0) return; int shownFailed = Math.min(currentFailedSources.length(), 20); resultList.addView(sectionTitle("منابع ناموفق — " + currentFailedSources.length() + " مورد")); for (int i = 0; i < shownFailed; i++) try { resultList.addView(failedSourceRow(currentFailedSources.getJSONObject(i))); } catch (Exception ignored) { } }
    private View pagerRow(int pageCount) { LinearLayout row = new LinearLayout(this); row.setOrientation(LinearLayout.HORIZONTAL); row.setPadding(0, dp(4), 0, dp(10)); row.setGravity(Gravity.CENTER_VERTICAL); row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); Button next = button("بعدی", accent); Button previous = button("قبلی", surface2); TextView page = label("صفحه " + (currentPage + 1) + " / " + pageCount, 13, text, true, true); page.setGravity(Gravity.CENTER); previous.setEnabled(currentPage > 0); next.setEnabled(currentPage < pageCount - 1); previous.setOnClickListener(v -> { if (currentPage > 0) { currentPage--; renderCurrentPage(); } }); next.setOnClickListener(v -> { if (currentPage < pageCount - 1) { currentPage++; renderCurrentPage(); } }); row.addView(next, weight()); row.addView(space(dp(8), 1)); row.addView(page, weight()); row.addView(space(dp(8), 1)); row.addView(previous, weight()); return row; }
    private boolean isXrayAvailable() { return new File(getApplicationInfo().nativeLibraryDir, "libxray.so").isFile(); }
    private void showError(Exception ex) { statusText.setText("خطا: " + ex.getMessage()); resultList.addView(resultRow("خطای موتور native Kotlin", String.valueOf(ex), "", false)); setBusy(false); }
    private void copyResults() { List<String> configs = collectFilteredConfigs(); ClipboardManager cm = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE); cm.setPrimaryClip(ClipData.newPlainText("v2ray configs", String.join("\n", configs))); statusText.setText(configs.size() + " کانفیگ کپی شد."); }
    private void copyOne(String config) { ClipboardManager cm = (ClipboardManager) getSystemService(Context.CLIPBOARD_SERVICE); cm.setPrimaryClip(ClipData.newPlainText("v2ray config", config)); statusText.setText("یک کانفیگ کپی شد."); }
    private void setBusy(boolean busy) { running = busy; startButton.setEnabled(!busy); stopButton.setEnabled(busy); copyButton.setEnabled(!busy && !collectFilteredConfigs().isEmpty()); tokenInput.setEnabled(!busy); limitInput.setEnabled(!busy); timeoutInput.setEnabled(!busy); healthBox.setEnabled(!busy); searchInput.setEnabled(!busy); protocolButton.setEnabled(!busy); if (realCheckBox != null) realCheckBox.setEnabled(!busy); if (refreshButton != null) refreshButton.setEnabled(!busy); startButton.setText(busy ? "در حال اسکن..." : "شروع اسکن"); progressBar.setIndeterminate(busy); if (!busy && !scanCancelled) progressBar.setProgress(100); }
    private void setStats(String fetched, String unique, String healthy, String scored) { fetchedText.setText(fetched); uniqueText.setText(unique); healthyText.setText(healthy); scoredText.setText(scored); }
    private CheckBox checkBox(String title, boolean checked) { CheckBox box = new CheckBox(this); box.setText(title); box.setChecked(checked); box.setTextColor(text); box.setTextSize(14); box.setGravity(Gravity.RIGHT | Gravity.CENTER_VERTICAL); box.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); return box; }
    private LinearLayout card(int color, int radius) { LinearLayout layout = new LinearLayout(this); layout.setPadding(dp(14), dp(14), dp(14), dp(14)); layout.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); GradientDrawable bgDrawable = new GradientDrawable(); bgDrawable.setColor(color); bgDrawable.setCornerRadius(dp(radius)); layout.setBackground(bgDrawable); LinearLayout.LayoutParams lp = matchWrap(); lp.setMargins(0, 0, 0, dp(12)); layout.setLayoutParams(lp); return layout; }
    private TextView label(String value, int size, int color, boolean bold, boolean rtl) { TextView tv = new TextView(this); tv.setText(value); tv.setTextSize(size); tv.setTextColor(color); tv.setGravity(rtl ? Gravity.RIGHT : Gravity.LEFT); tv.setTextDirection(rtl ? View.TEXT_DIRECTION_RTL : View.TEXT_DIRECTION_LTR); if (bold) tv.setTypeface(Typeface.DEFAULT, Typeface.BOLD); return tv; }
    private LinearLayout inputGroup(String title, String description, EditText input) { LinearLayout group = new LinearLayout(this); group.setOrientation(LinearLayout.VERTICAL); group.setLayoutDirection(View.LAYOUT_DIRECTION_RTL); TextView titleView = label(title, 13, text, true, true); TextView descView = label(description, 10, muted, false, true); descView.setPadding(0, 0, 0, dp(6)); group.addView(titleView); group.addView(descView); group.addView(input, matchHeight(46)); return group; }
    private EditText input(String hint, boolean password, boolean rtl) { EditText input = new EditText(this); input.setHint(hint); input.setHintTextColor(muted); input.setTextColor(text); input.setSingleLine(true); input.setTextSize(14); input.setPadding(dp(12), 0, dp(12), 0); input.setGravity(rtl ? Gravity.RIGHT | Gravity.CENTER_VERTICAL : Gravity.LEFT | Gravity.CENTER_VERTICAL); input.setTextDirection(rtl ? View.TEXT_DIRECTION_RTL : View.TEXT_DIRECTION_LTR); input.setInputType(password ? (InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD) : InputType.TYPE_CLASS_TEXT); GradientDrawable bgDrawable = new GradientDrawable(); bgDrawable.setColor(surface2); bgDrawable.setCornerRadius(dp(14)); input.setBackground(bgDrawable); return input; }
    private Button button(String title, int color) { Button btn = new Button(this); btn.setText(title); btn.setAllCaps(false); btn.setTextColor(text); btn.setTextSize(14); btn.setTypeface(Typeface.DEFAULT, Typeface.BOLD); GradientDrawable bgDrawable = new GradientDrawable(); bgDrawable.setColor(color); bgDrawable.setCornerRadius(dp(14)); btn.setBackground(bgDrawable); return btn; }
    private TextView statCard(String title, LinearLayout parent) { LinearLayout card = new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(10), dp(8), dp(10), dp(8)); card.setGravity(Gravity.RIGHT); GradientDrawable bgDrawable = new GradientDrawable(); bgDrawable.setColor(surface); bgDrawable.setCornerRadius(dp(16)); card.setBackground(bgDrawable); TextView top = label(title, 10, muted, false, true); TextView value = label("0", 20, text, true, false); card.addView(top); card.addView(value); LinearLayout.LayoutParams lp = weight(); lp.setMargins(dp(3), 0, dp(3), 0); parent.addView(card, lp); return value; }
    private View sectionTitle(String value) { TextView tv = label(value, 15, text, true, true); tv.setPadding(dp(2), 0, dp(2), dp(10)); return tv; }
    private View resultRow(String line1, String line2, String config, boolean canCopy) { LinearLayout row = card(surface, 18); row.setOrientation(LinearLayout.VERTICAL); row.addView(label(line1, 14, text, true, true)); row.addView(label(line2, 12, muted, false, true)); if (config != null && !config.isEmpty()) { TextView cfg = label(config, 10, muted, false, false); cfg.setTypeface(Typeface.MONOSPACE); cfg.setMaxLines(3); cfg.setPadding(0, dp(8), 0, dp(4)); row.addView(cfg); } if (canCopy && config != null && !config.isEmpty()) { Button copy = button("کپی این کانفیگ", surface2); copy.setOnClickListener(v -> copyOne(config)); LinearLayout.LayoutParams lp = matchHeight(42); lp.setMargins(0, dp(8), 0, 0); row.addView(copy, lp); } return row; }
    private View infoRow(String title, String body) { LinearLayout row = card(surface3, 18); row.setOrientation(LinearLayout.VERTICAL); row.addView(label(title, 13, text, true, true)); row.addView(label(body, 12, muted, false, true)); return row; }
    private View failedSourceRow(JSONObject failed) { LinearLayout row = card(surface3, 18); row.setOrientation(LinearLayout.VERTICAL); String message = failed.optString("message", failed.optString("error", "خطای نامشخص")); String url = failed.optString("url", ""); row.addView(label("خطای منبع", 14, warning, true, true)); row.addView(label(shortMessage(message), 12, text, false, true)); TextView source = label(shortUrl(url), 10, muted, false, false); source.setTypeface(Typeface.MONOSPACE); source.setMaxLines(2); source.setPadding(0, dp(6), 0, 0); row.addView(source); return row; }
    private String shortMessage(String message) { if (message == null || message.trim().isEmpty()) return "پیام خطا موجود نیست."; String m = message.replace('\n', ' ').trim(); return m.length() > 140 ? m.substring(0, 140) + "…" : m; }
    private String shortUrl(String url) { if (url == null || url.trim().isEmpty()) return "source: unknown"; return url.length() > 120 ? url.substring(0, 120) + "…" : url; }
    private View space(int width, int height) { View v = new View(this); v.setLayoutParams(new LinearLayout.LayoutParams(width, height)); return v; }
    private LinearLayout.LayoutParams matchWrap() { return new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT); }
    private LinearLayout.LayoutParams matchHeight(int height) { return new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, dp(height)); }
    private LinearLayout.LayoutParams weight() { return new LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f); }
    private int dp(int value) { return Math.round(value * getResources().getDisplayMetrics().density); }
    private int parseInt(String value, int fallback) { try { return Integer.parseInt(value.trim()); } catch (Exception ignored) { return fallback; } }
    private double parseDouble(String value, double fallback) { try { return Double.parseDouble(value.trim()); } catch (Exception ignored) { return fallback; } }
}
