package org.mehdimt.v2rayfinder.registry

/**
 * Kotlin representation of one runtime source registry record.
 *
 * The registry is generated by v2ray-source-hunter and synced into this app as
 * registry/sources.json. Unknown JSON fields are intentionally ignored by the
 * parser so the hunter can add metadata without breaking the Android runtime.
 */
data class SourceRecord(
    val id: String,
    val label: String,
    val url: String,
    val sourceType: String = "static_subscription",
    val trust: String = "low",
    val status: String = "candidate",
    val enabled: Boolean = true,
    val tags: List<String> = emptyList(),
    val protocols: List<String> = emptyList(),
    val notes: String = "",
    val region: String = "",
    val addedAt: String = "",
    val lastReviewedAt: String = "",
    val upstreamUrl: String = "",
) {
    val isActive: Boolean
        get() = enabled && status.lowercase() in ACTIVE_STATUSES

    companion object {
        val ACTIVE_STATUSES: Set<String> = setOf("official", "trusted")
        val CANDIDATE_STATUSES: Set<String> = setOf("candidate", "experimental")
        val INACTIVE_STATUSES: Set<String> = setOf("quarantine", "disabled")
    }
}
